spring:
  application:
    name: "booking"
  datasource:
    username: root
    password: Root
    url: jdbc:mysql://localhost:3306/testenvironment
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true